BaseUrl= "https://rushail.github.io/"
LanguageCode= "en-US"
Title= "Rushail Khan"
paginate = 10
DisqusShortname = ""
Copyright = "All rights reserved - 2021"
canonifyurls = true
theme = "hugo-theme-air"

[author]
  name = "rushail"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "this is my personal blog site"
  cover = "images/user.jpg"
  author = "rushail"
  authorlocation = ""
  authorwebsite = "https://rushail.github.io/"
  bio= "oh what a world"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "rushail"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]